# Generated by Django 5.1.3 on 2024-12-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0003_room_alter_text_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messager.room'),
        ),
    ]
