# Generated by Django 5.1.3 on 2024-12-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0004_profile_alter_text_receiver_alter_text_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='I HAVE NOTTTING!!!', max_length=500),
        ),
    ]
