# Generated by Django 5.1.3 on 2024-12-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0004_alter_text_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
