# Generated by Django 5.1.3 on 2024-12-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0005_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfnew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='static/images/defaultpfp.webp', null=True, upload_to='media/'),
        ),
    ]
