# Generated by Django 5.1.3 on 2024-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0006_profile_pfnew_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='media/'),
        ),
    ]
