# Generated by Django 5.1.3 on 2024-12-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0006_alter_room_name_alter_text_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
