# Generated by Django 5.1.3 on 2024-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0007_alter_profile_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pfnew',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pfp',
        ),
        migrations.AddField(
            model_name='profile',
            name='pfimage',
            field=models.ImageField(default='NA', upload_to='media/'),
        ),
    ]
