# Generated by Django 5.1.3 on 2024-12-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0008_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
