# Generated by Django 5.1.3 on 2024-12-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0009_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
